version: '3'
services:
  network:
    image: hivecell/pygrid-network:latest 
    build: ./apps/network
    environment:
      - PORT=7000
      - SECRET_KEY=ineedtoputasecrethere
      - DATABASE_URL=sqlite:///databasenetwork.db
    ports:
      - 7000:7000

  alice:
    image: hivecell/pygrid-node:latest 
    build: ./apps/node
    environment:
      - NODE_ID=Alice
      - ADDRESS=http://alice:5000/
      - PORT=5000
      - NETWORK=http://network:7000
      - DATABASE_URL=sqlite:///databasenode.db
      - LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1
    depends_on:
      - 'network'
    ports:
      - 5000:5000

  bob:
    image: hivecell/pygrid-node:latest 
    build: ./apps/node
    environment:
      - NODE_ID=Bob
      - ADDRESS=http://bob:5001/
      - PORT=5001
      - NETWORK=http://network:7000
      - DATABASE_URL=sqlite:///databasenode.db
      - LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1
    depends_on:
      - 'network'
    ports:
      - 5001:5001

  charlie:
    image: hivecell/pygrid-node:latest
    build: ./apps/node
    environment:
      - NODE_ID=Charlie
      - ADDRESS=http://charlie:5002/
      - PORT=5002
      - NETWORK=http://network:7000
      - DATABASE_URL=sqlite:///databasenode.db
      - LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1
    depends_on:
      - 'network'
    ports:
      - 5002:5002

  dan:
    image: hivecell/pygrid-node:latest
    build: ./apps/node
    environment:
      - NODE_ID=Dan
      - ADDRESS=http://dan:5003/
      - PORT=5003
      - NETWORK=http://network:7000
      - DATABASE_URL=sqlite:///databasenode.db
      - LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1
    depends_on:
      - 'network'
    ports:
      - 5003:5003

  jupyter:
    image: hivecell/pysyft:notebook
    build: ./apps/notebook
    ports:
      - 8888:8888
    volumes:
      - ./examples:/workspace/examples
